# Site Build Settings
title: "AMAR POTDAR"
description: "Thoughts, Experiences, Projects"
author: "meamarp"
url: https://meamarp.github.io/

# Long-Haul Theme Configuration
baseurl: # Only necessary when hosting in a sub-directory

# Build settings
markdown: kramdown
highlighter: rouge
permalink: blog/:title/
paginate_path: "blog/page:num/"

# jekyll-paginate configuration
paginate: 5

# Plugins
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Sass
sass:
  style: compressed

# Navigation Menu
navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

# Social Media
social:
  github: meamarp
  twitter: 
  facebook: 
  email: 
  linkedin: 
  youtube: 
  tumblr: 

# Google Analytics (optional)
google_analytics: 

# Disqus Comments (optional)
disqus:
  shortname:
